artifacts:
  "@daiyam/artifact-lang-js":
    version: 0.9.4
    provides:
      - "20"
  "@daiyam/artifact-lang-ts":
    version: 0.6.3
  "@daiyam/artifact-npm-ts":
    version: 0.4.3
  "@daiyam/artifact-npm-daiyam":
    version: 0.2.3
  "@daiyam/artifact-npm-cli-ts":
    version: 0.5.1
